version: '3'

services:
  web:
    build: .
    container_name: async_download_service
    command: sh -c "python3 server.py"
    volumes:
      - .:/async-download-service/
    restart: 'no'
    ports:
      - "8080:8080"